# SageMaker-E2E-Workshop


SageMaker End 2 End Workshop

Issue in setting up fastai kernel - in Jupyter notebook

Once you start and stop - this is gone

sh-4.2$ ls -al /home/ec2-user/SageMaker/fastai/courses/dl1/data
ls: cannot access /home/ec2-user/SageMaker/fastai/courses/dl1/data: No such file or directory
sh-4.2$
